//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGH.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TGH.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عمان - الأردن.
        /// </summary>
        internal static string ADDRESS_AMMAN {
            get {
                return ResourceManager.GetString("ADDRESS_AMMAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكل.
        /// </summary>
        internal static string ALL {
            get {
                return ResourceManager.GetString("ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كل الجمعيات.
        /// </summary>
        internal static string CHARITIES_ALL {
            get {
                return ResourceManager.GetString("CHARITIES_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة باسماء الجمعيات المشتركة في منصة معاً.
        /// </summary>
        internal static string CHARITIES_ALL_DESCRIPTION {
            get {
                return ResourceManager.GetString("CHARITIES_ALL_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الجمعيات.
        /// </summary>
        internal static string CHARITIES_COUNT {
            get {
                return ResourceManager.GetString("CHARITIES_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المحادثات.
        /// </summary>
        internal static string CHAT_CONVERSATIONS {
            get {
                return ResourceManager.GetString("CHAT_CONVERSATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل أنت متأكد من حذف هذه الرسالة؟.
        /// </summary>
        internal static string CHAT_DELETE_CONFIRM {
            get {
                return ResourceManager.GetString("CHAT_DELETE_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل رسالة.
        /// </summary>
        internal static string CHAT_ENTERMESSAGE {
            get {
                return ResourceManager.GetString("CHAT_ENTERMESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد رسائل، اضغط على محادثة.
        /// </summary>
        internal static string CHAT_NOMESSAGES {
            get {
                return ResourceManager.GetString("CHAT_NOMESSAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضغط على محادثة.
        /// </summary>
        internal static string CHAT_PICKCONVERSATION {
            get {
                return ResourceManager.GetString("CHAT_PICKCONVERSATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إغلاق.
        /// </summary>
        internal static string CLOSE {
            get {
                return ResourceManager.GetString("CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        internal static string CONTACT_ADDRESS {
            get {
                return ResourceManager.GetString("CONTACT_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني.
        /// </summary>
        internal static string CONTACT_EMAIL {
            get {
                return ResourceManager.GetString("CONTACT_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرسالة.
        /// </summary>
        internal static string CONTACT_MESSAGE {
            get {
                return ResourceManager.GetString("CONTACT_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم.
        /// </summary>
        internal static string CONTACT_NAME {
            get {
                return ResourceManager.GetString("CONTACT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف.
        /// </summary>
        internal static string CONTACT_PHONENUMBER {
            get {
                return ResourceManager.GetString("CONTACT_PHONENUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        internal static string CONTACT_SUBJECT {
            get {
                return ResourceManager.GetString("CONTACT_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أيام.
        /// </summary>
        internal static string DAYS {
            get {
                return ResourceManager.GetString("DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل أنت متأكد من حذف هذا التبرع ؟.
        /// </summary>
        internal static string DONATION_DELETE_CONFIRM {
            get {
                return ResourceManager.GetString("DONATION_DELETE_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نموذج التبرع العيني.
        /// </summary>
        internal static string DONATION_FORM {
            get {
                return ResourceManager.GetString("DONATION_FORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التصنيف.
        /// </summary>
        internal static string DONATION_FORM_CATEGORY {
            get {
                return ResourceManager.GetString("DONATION_FORM_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف.
        /// </summary>
        internal static string DONATION_FORM_DESCRIPTION {
            get {
                return ResourceManager.GetString("DONATION_FORM_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صورة التبرع.
        /// </summary>
        internal static string DONATION_FORM_PICTURE {
            get {
                return ResourceManager.GetString("DONATION_FORM_PICTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم التبرع.
        /// </summary>
        internal static string DONATION_FORM_TITLE {
            get {
                return ResourceManager.GetString("DONATION_FORM_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تبرع جديد.
        /// </summary>
        internal static string DONATION_NEW {
            get {
                return ResourceManager.GetString("DONATION_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إظهار الاسم في التبرع.
        /// </summary>
        internal static string DONATION_SHOWMYNAME {
            get {
                return ResourceManager.GetString("DONATION_SHOWMYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سياسات التبرع.
        /// </summary>
        internal static string DONATIONCONDITIONS {
            get {
                return ResourceManager.GetString("DONATIONCONDITIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ بتسجيل الدخول.
        /// </summary>
        internal static string ERROR_LOGGINGIN {
            get {
                return ResourceManager.GetString("ERROR_LOGGINGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ بتحديث الملف.
        /// </summary>
        internal static string ERROR_UPDATEFAILED {
            get {
                return ResourceManager.GetString("ERROR_UPDATEFAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلغاء.
        /// </summary>
        internal static string FORM_CANCEL {
            get {
                return ResourceManager.GetString("FORM_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المحافظة.
        /// </summary>
        internal static string FORM_CITY {
            get {
                return ResourceManager.GetString("FORM_CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد كلمة السر.
        /// </summary>
        internal static string FORM_CONFIRMPASSWORD {
            get {
                return ResourceManager.GetString("FORM_CONFIRMPASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل أنت متأكد من حذف الصورة؟.
        /// </summary>
        internal static string FORM_DELETEPICTURE {
            get {
                return ResourceManager.GetString("FORM_DELETEPICTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف.
        /// </summary>
        internal static string FORM_DESCRIPTION {
            get {
                return ResourceManager.GetString("FORM_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل الملف.
        /// </summary>
        internal static string FORM_EDITPROFILE {
            get {
                return ResourceManager.GetString("FORM_EDITPROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني.
        /// </summary>
        internal static string FORM_EMAIL {
            get {
                return ResourceManager.GetString("FORM_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الكامل.
        /// </summary>
        internal static string FORM_FULLNAME {
            get {
                return ResourceManager.GetString("FORM_FULLNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة السر الجديدة.
        /// </summary>
        internal static string FORM_NEWPASSWORD {
            get {
                return ResourceManager.GetString("FORM_NEWPASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد كلمة السر الجديدة.
        /// </summary>
        internal static string FORM_NEWPASSWORDCONFIRM {
            get {
                return ResourceManager.GetString("FORM_NEWPASSWORDCONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنبيه.
        /// </summary>
        internal static string FORM_NOTE {
            get {
                return ResourceManager.GetString("FORM_NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جميع المعلومات الشخصية سرية ولا يتم مشاركتها مع أي جهة هي فقط لاستخدام إدارة المنصة لتواصل بين الأطراف يتم من خلال المحادثة النصية المباشرة من خلال نافذة محادثة خاصة.
        /// </summary>
        internal static string FORM_NOTE_MESSAGE {
            get {
                return ResourceManager.GetString("FORM_NOTE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة السر الحالية.
        /// </summary>
        internal static string FORM_OLDPASSWORD {
            get {
                return ResourceManager.GetString("FORM_OLDPASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة السر.
        /// </summary>
        internal static string FORM_PASSWORD {
            get {
                return ResourceManager.GetString("FORM_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملف الشخصي.
        /// </summary>
        internal static string FORM_PERSONALINFO {
            get {
                return ResourceManager.GetString("FORM_PERSONALINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف.
        /// </summary>
        internal static string FORM_PHONE {
            get {
                return ResourceManager.GetString("FORM_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصورة الشخصية.
        /// </summary>
        internal static string FORM_PICTURE {
            get {
                return ResourceManager.GetString("FORM_PICTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        internal static string FORM_SAVE {
            get {
                return ResourceManager.GetString("FORM_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الدخول.
        /// </summary>
        internal static string FORM_SIGNIN {
            get {
                return ResourceManager.GetString("FORM_SIGNIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع المستخدم.
        /// </summary>
        internal static string FORM_TYPE {
            get {
                return ResourceManager.GetString("FORM_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحميل.
        /// </summary>
        internal static string FORM_UPLOAD {
            get {
                return ResourceManager.GetString("FORM_UPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تواصل.
        /// </summary>
        internal static string HOME_CHATNOW {
            get {
                return ResourceManager.GetString("HOME_CHATNOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تبرع الآن.
        /// </summary>
        internal static string HOME_DONATENOW {
            get {
                return ResourceManager.GetString("HOME_DONATENOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التبرعات العينية.
        /// </summary>
        internal static string HOME_DONATIONS {
            get {
                return ResourceManager.GetString("HOME_DONATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معا.
        /// </summary>
        internal static string HOME_MA3AN {
            get {
                return ResourceManager.GetString("HOME_MA3AN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ما قد يفيض عن حاجتك وما لم يعد ضروري لديك قد يكون حاجة ملحة او ضرورية لشخص اخر
        ///                وترسم ابتسامة على وجه طفل بريء او انسان عاجز او غير مقتدر
        ///                قد ترغب بمفجأة صديق أو قريب بهدية او ان تساعد شخص بمنحة دراسية او تامين فرصة عمل تجد ذلك في منصة &quot;معا&quot;.
        /// </summary>
        internal static string HOME_MA3ANDESCRIPTION {
            get {
                return ResourceManager.GetString("HOME_MA3ANDESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البحث عن محافظة.
        /// </summary>
        internal static string HOME_SEARCHCITY {
            get {
                return ResourceManager.GetString("HOME_SEARCHCITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستفيد.
        /// </summary>
        internal static string HOME_TEXT1 {
            get {
                return ResourceManager.GetString("HOME_TEXT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أكثر من.
        /// </summary>
        internal static string HOME_TEXT2_1 {
            get {
                return ResourceManager.GetString("HOME_TEXT2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متبرع.
        /// </summary>
        internal static string HOME_TEXT2_2 {
            get {
                return ResourceManager.GetString("HOME_TEXT2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التبرعات.
        /// </summary>
        internal static string HOME_TITLE_1 {
            get {
                return ResourceManager.GetString("HOME_TITLE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العينية.
        /// </summary>
        internal static string HOME_TITLE_2 {
            get {
                return ResourceManager.GetString("HOME_TITLE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعات.
        /// </summary>
        internal static string HOURS {
            get {
                return ResourceManager.GetString("HOURS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العربية.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نموذج تسجيل الدخول.
        /// </summary>
        internal static string LOGIN_FORM {
            get {
                return ResourceManager.GetString("LOGIN_FORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دقائق.
        /// </summary>
        internal static string MINUTES {
            get {
                return ResourceManager.GetString("MINUTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عن معا.
        /// </summary>
        internal static string NAV_ABOUT {
            get {
                return ResourceManager.GetString("NAV_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجمعيات الخيرية.
        /// </summary>
        internal static string NAV_CHARITIES {
            get {
                return ResourceManager.GetString("NAV_CHARITIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اتصل بنا.
        /// </summary>
        internal static string NAV_CONTACTUS {
            get {
                return ResourceManager.GetString("NAV_CONTACTUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لوحة التحكم.
        /// </summary>
        internal static string NAV_CONTROLPANEL {
            get {
                return ResourceManager.GetString("NAV_CONTROLPANEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل حساب جديد.
        /// </summary>
        internal static string NAV_CREATE_NEWACCOUNT {
            get {
                return ResourceManager.GetString("NAV_CREATE_NEWACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرئيسية.
        /// </summary>
        internal static string NAV_HOME {
            get {
                return ResourceManager.GetString("NAV_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محادثاتي.
        /// </summary>
        internal static string NAV_MYCHATS {
            get {
                return ResourceManager.GetString("NAV_MYCHATS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تبرعاتي.
        /// </summary>
        internal static string NAV_MYDONATIONS {
            get {
                return ResourceManager.GetString("NAV_MYDONATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بياناتي الشخصية.
        /// </summary>
        internal static string NAV_MYPROFILE {
            get {
                return ResourceManager.GetString("NAV_MYPROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستخدم جديد.
        /// </summary>
        internal static string NAV_NEWACCOUNT {
            get {
                return ResourceManager.GetString("NAV_NEWACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغيير كلمة السر.
        /// </summary>
        internal static string NAV_PASSWORD {
            get {
                return ResourceManager.GetString("NAV_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستخدم جديد.
        /// </summary>
        internal static string NAV_REGISTER {
            get {
                return ResourceManager.GetString("NAV_REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل دخول.
        /// </summary>
        internal static string NAV_SIGNIN {
            get {
                return ResourceManager.GetString("NAV_SIGNIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل خروج.
        /// </summary>
        internal static string NAV_SIGNOUT {
            get {
                return ResourceManager.GetString("NAV_SIGNOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الآن.
        /// </summary>
        internal static string NOW {
            get {
                return ResourceManager.GetString("NOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال.
        /// </summary>
        internal static string SEND {
            get {
                return ResourceManager.GetString("SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عن.
        /// </summary>
        internal static string TITLE_ABOUT_1 {
            get {
                return ResourceManager.GetString("TITLE_ABOUT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معا.
        /// </summary>
        internal static string TITLE_ABOUT_2 {
            get {
                return ResourceManager.GetString("TITLE_ABOUT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجمعيات.
        /// </summary>
        internal static string TITLE_CHARITIES_1 {
            get {
                return ResourceManager.GetString("TITLE_CHARITIES_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخيرية.
        /// </summary>
        internal static string TITLE_CHARITIES_2 {
            get {
                return ResourceManager.GetString("TITLE_CHARITIES_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اتصل.
        /// </summary>
        internal static string TITLE_CONTACT_1 {
            get {
                return ResourceManager.GetString("TITLE_CONTACT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بنا.
        /// </summary>
        internal static string TITLE_CONTACT_2 {
            get {
                return ResourceManager.GetString("TITLE_CONTACT_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التبرعات.
        /// </summary>
        internal static string TITLE_DONATIONS_1 {
            get {
                return ResourceManager.GetString("TITLE_DONATIONS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العينية.
        /// </summary>
        internal static string TITLE_DONATIONS_2 {
            get {
                return ResourceManager.GetString("TITLE_DONATIONS_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن يكون {0} أكثر من {2} خانات و أقل من {1} خانة.
        /// </summary>
        internal static string VALIATION_DESCRIPTION_REGEX {
            get {
                return ResourceManager.GetString("VALIATION_DESCRIPTION_REGEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف موجود مسبقا.
        /// </summary>
        internal static string VALIDATION_ALREADYEXISTS {
            get {
                return ResourceManager.GetString("VALIDATION_ALREADYEXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب اختيار التصنيف.
        /// </summary>
        internal static string VALIDATION_CATEGORY_REQUIRED {
            get {
                return ResourceManager.GetString("VALIDATION_CATEGORY_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب اختيار المحافظة.
        /// </summary>
        internal static string VALIDATION_CITY_REQUIRED {
            get {
                return ResourceManager.GetString("VALIDATION_CITY_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن تطابق كلمة السر.
        /// </summary>
        internal static string VALIDATION_CONFIRMPASSWORD_REQUIRED {
            get {
                return ResourceManager.GetString("VALIDATION_CONFIRMPASSWORD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string VALIDATION_DESCRIPTION_REQUIRED {
            get {
                return ResourceManager.GetString("VALIDATION_DESCRIPTION_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدخال البريد الإلكتروني.
        /// </summary>
        internal static string VALIDATION_EMAIL_REQUIRED {
            get {
                return ResourceManager.GetString("VALIDATION_EMAIL_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدخال الاسم الكامل.
        /// </summary>
        internal static string VALIDATION_FULLNAME_REQUIRED {
            get {
                return ResourceManager.GetString("VALIDATION_FULLNAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال كلمة المرور الجديدة.
        /// </summary>
        internal static string VALIDATION_NEWPASSWORD_REQUIRED {
            get {
                return ResourceManager.GetString("VALIDATION_NEWPASSWORD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال كلمة السر الحالية.
        /// </summary>
        internal static string VALIDATION_OLDPASSWORD_REQUIRED {
            get {
                return ResourceManager.GetString("VALIDATION_OLDPASSWORD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن تحتوي كلمة السر على حروف وأرقام ورمز.
        /// </summary>
        internal static string VALIDATION_PASSWORD_REGEX {
            get {
                return ResourceManager.GetString("VALIDATION_PASSWORD_REGEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال كلمة المرور.
        /// </summary>
        internal static string VALIDATION_PASSWORD_REQUIRED {
            get {
                return ResourceManager.GetString("VALIDATION_PASSWORD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدخال رقم الهاتف.
        /// </summary>
        internal static string VALIDATION_PHONE_REQUIRED {
            get {
                return ResourceManager.GetString("VALIDATION_PHONE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن يكون {0} أكثر من {2} خانات و أقل من {1} خانة.
        /// </summary>
        internal static string VALIDATION_REGEX {
            get {
                return ResourceManager.GetString("VALIDATION_REGEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدخال بريد إلكتروني صحيح.
        /// </summary>
        internal static string VALIDATION_REGEX_EMAIL {
            get {
                return ResourceManager.GetString("VALIDATION_REGEX_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدخال رقم هاتف صحيح.
        /// </summary>
        internal static string VALIDATION_REGEX_PHONENUMBER {
            get {
                return ResourceManager.GetString("VALIDATION_REGEX_PHONENUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن يكون {0} أكثر من {2} خانات و أقل من {1} خانة.
        /// </summary>
        internal static string VALIDATION_TITLE_REGEX {
            get {
                return ResourceManager.GetString("VALIDATION_TITLE_REGEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال العنوان.
        /// </summary>
        internal static string VALIDATION_TITLE_REQUIRED {
            get {
                return ResourceManager.GetString("VALIDATION_TITLE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى اختيار نوع المستخدم.
        /// </summary>
        internal static string VALIDATION_TYPE_REQUIRED {
            get {
                return ResourceManager.GetString("VALIDATION_TYPE_REQUIRED", resourceCulture);
            }
        }

    }
}
